# N - Grams :-->

An n-gram is a sequence of n adjacent symbols, which could be letters, syllables, words, or even phonemes or base pairs

In [1]:
# Importing Required Libraries

import pandas as pd
import re
import nltk
from nltk.stem import WordNetLemmatizer

Initializing the Count vectorizer and Lemmatizer

In [2]:
Lemmatizer = WordNetLemmatizer()
Messages = []
Stop_Words = ["is" ,"that", "this", "the" , "a" , "i" , "if" , "it", "did" , "can" , "with", "but" , "for" , "to" , "in",
              "his" , "our" , "and" , "will" , "on"]

Reading the Data

In [3]:
Data = pd.read_csv("Spam Classification.csv")

In [4]:
Data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
Data.tail()

Category                                            Message
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

In [6]:
Data.describe()

Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [7]:
for i in range (len(Data)):
    Cleaned = re.sub("[^a-zA-Z]" , " ", Data['Message'][i])
    Cleaned = Cleaned.lower()
    Cleaned = Cleaned.split()
    Lemmatized = [Lemmatizer.lemmatize(word) for word in Cleaned if not word in Stop_Words]
    Cleaned = " ".join(Lemmatized)
    Messages.append(Cleaned)

In [8]:
Messages

['go until jurong point crazy available only bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah don t think he go usf he life around here though',
 'freemsg hey there darling s been week s now no word back d like some fun you up still tb ok xxx std chgs send rcv',
 'even my brother not like speak me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune all caller press copy your friend callertune',
 'winner a valued network customer you have been selected receivea prize reward claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled update latest colour mobile camera free call mobile update co free',
 'm gonna be home soon don t want talk about stuff anymore tonight k ve cried 

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
Count_Vectorizer = CountVectorizer(max_features=200, binary=True)

BOW = Count_Vectorizer.fit_transform(Messages).toarray()
BOW

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 200))

It will show the indexes of the words

In [11]:
Count_Vectorizer.vocabulary_

{'go': np.int64(51),
 'only': np.int64(117),
 'great': np.int64(56),
 'there': np.int64(157),
 'got': np.int64(55),
 'wat': np.int64(176),
 'ok': np.int64(115),
 'free': np.int64(46),
 'win': np.int64(188),
 'text': np.int64(153),
 'txt': np.int64(166),
 'over': np.int64(120),
 'say': np.int64(133),
 'so': np.int64(142),
 'already': np.int64(4),
 'then': np.int64(156),
 'don': np.int64(39),
 'think': np.int64(160),
 'he': np.int64(64),
 'life': np.int64(83),
 'around': np.int64(13),
 'here': np.int64(67),
 'hey': np.int64(68),
 'been': np.int64(19),
 'week': np.int64(179),
 'now': np.int64(110),
 'no': np.int64(107),
 'word': np.int64(191),
 'back': np.int64(17),
 'like': np.int64(84),
 'some': np.int64(143),
 'you': np.int64(198),
 'up': np.int64(168),
 'still': np.int64(148),
 'send': np.int64(135),
 'even': np.int64(41),
 'my': np.int64(101),
 'not': np.int64(109),
 'me': np.int64(91),
 'they': np.int64(158),
 'per': np.int64(121),
 'your': np.int64(199),
 'ha': np.int64(60),
 'all'

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
Count_Vectorizer = CountVectorizer(max_features=1000, binary=True ,ngram_range=(1,2))

BOW = Count_Vectorizer.fit_transform(Messages).toarray()
BOW

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 1000))

In [17]:
Count_Vectorizer.vocabulary_

{'go': np.int64(300),
 'until': np.int64(843),
 'point': np.int64(637),
 'crazy': np.int64(167),
 'available': np.int64(51),
 'only': np.int64(586),
 'great': np.int64(314),
 'world': np.int64(939),
 'there': np.int64(790),
 'got': np.int64(312),
 'wat': np.int64(877),
 'ok': np.int64(577),
 'lar': np.int64(424),
 'wif': np.int64(918),
 'free': np.int64(268),
 'entry': np.int64(233),
 'wkly': np.int64(929),
 'win': np.int64(921),
 'final': np.int64(254),
 'st': np.int64(745),
 'may': np.int64(483),
 'text': np.int64(778),
 'receive': np.int64(669),
 'question': np.int64(657),
 'txt': np.int64(832),
 'rate': np.int64(660),
 'apply': np.int64(37),
 'over': np.int64(606),
 'free entry': np.int64(270),
 'dun': np.int64(219),
 'say': np.int64(688),
 'so': np.int64(733),
 'early': np.int64(223),
 'already': np.int64(19),
 'then': np.int64(789),
 'don': np.int64(201),
 'think': np.int64(795),
 'he': np.int64(350),
 'life': np.int64(441),
 'around': np.int64(42),
 'here': np.int64(359),
 'thou

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
Count_Vectorizer = CountVectorizer(max_features=1000, binary=True ,ngram_range=(1,3))

BOW = Count_Vectorizer.fit_transform(Messages).toarray()
BOW

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 1000))

In [19]:
Count_Vectorizer.vocabulary_

{'go': np.int64(300),
 'until': np.int64(834),
 'point': np.int64(635),
 'crazy': np.int64(168),
 'available': np.int64(52),
 'only': np.int64(585),
 'great': np.int64(312),
 'world': np.int64(936),
 'there': np.int64(786),
 'got': np.int64(310),
 'wat': np.int64(870),
 'ok': np.int64(576),
 'lar': np.int64(426),
 'wif': np.int64(915),
 'free': np.int64(269),
 'entry': np.int64(233),
 'wkly': np.int64(926),
 'win': np.int64(918),
 'final': np.int64(255),
 'st': np.int64(744),
 'may': np.int64(489),
 'text': np.int64(774),
 'receive': np.int64(668),
 'question': np.int64(656),
 'txt': np.int64(827),
 'rate': np.int64(659),
 'apply': np.int64(36),
 'over': np.int64(606),
 'free entry': np.int64(271),
 'dun': np.int64(220),
 'say': np.int64(688),
 'so': np.int64(731),
 'early': np.int64(224),
 'already': np.int64(18),
 'then': np.int64(785),
 'don': np.int64(202),
 'think': np.int64(791),
 'he': np.int64(351),
 'life': np.int64(445),
 'around': np.int64(43),
 'here': np.int64(360),
 'thou

* As we are trying it with different N gram range

* Each gave us a differetn combintion of the words 

### Here's a more detailed breakdown of the advantages:


##### Contextual Understanding:
N-grams capture contextual meaning by considering the relationships between words in a sequence. This allows for a more nuanced understanding of text compared to analyzing individual words in isolation. 

##### Predictive Power:
N-gram models can predict the likelihood of a word appearing based on the preceding words, making them useful in tasks like text prediction and language generation. 

##### Ease of Implementation:
N-grams are relatively simple to implement and understand, as they involve counting the frequency of word sequences. 

##### Versatile Applications:
N-grams find use in various fields, including speech recognition, machine translation, sentiment analysis, and predictive text input. 

##### Improved Accuracy:
By considering context and word relationships, n-grams can improve the accuracy of various NLP tasks, such as part-of-speech tagging, sentiment analysis, and text classification. 

##### Reduced Resource Requirements:
N-gram indexes can reduce the computational resources needed to analyze large text datasets, making it efficient for handling large volumes of data. 